repos:
  # 1. Organiza os imports primeiro
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort

  # 2. Formata o código depois
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black

  # 3. Faz linting e correções adicionais no final
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args:
          - --max-line-length=88
          - --ignore=E203,W503,E501
