name: Validate Pull Request Source

on:
  pull_request:
    branches:
      - Master
      - Homologação
      - Produção

jobs:
  check_pr_source:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Source
        env:
          BASE_BRANCH: ${{ github.base_ref }}
          HEAD_BRANCH: ${{ github.head_ref }}
        run: |
          # Verifica se o PR para Master vem de uma ramificação com prefixo do Jira
          if [[ "$BASE_BRANCH" == "Master" && ! "$HEAD_BRANCH" =~ ^RH-[0-9]+- || "$HEAD_BRANCH" =~ ^RHTI-[0-9]+- ]]; then
            echo "PRs for Master should only come from branches with a Jira task prefix (e.g., JIRA-1234-feature)."
            exit 1
          fi
          
          # Verifica se o PR para Homologação vem de Master
          if [[ "$BASE_BRANCH" == "Homologação" && "$HEAD_BRANCH" != "Master" ]]; then
            echo "PRs for Homologação should only come from Master."
            exit 1
          fi
          
          # Verifica se o PR para Produção vem de Homologação
          if [[ "$BASE_BRANCH" == "Produção" && "$HEAD_BRANCH" != "Homologação" ]]; then
            echo "PRs for Produção should only come from Homologação."
            exit 1
          fi
